// PDF export utility for We Care system

export function generatePDFContent(reportType, data) {
  let content = ""

  switch (reportType) {
    case "summary":
      content = generateSummaryPDF(data)
      break
    case "claims":
      content = generateClaimsPDF(data)
      break
    case "users":
      content = generateUsersPDF(data)
      break
    case "department":
      content = generateDepartmentPDF(data)
      break
    case "audit":
      content = generateAuditPDF(data)
      break
    default:
      content = "Unknown report type"
  }

  return content
}

export function generatePDFHTML(reportType, data, user) {
  let htmlContent = ""

  switch (reportType) {
    case "summary":
      htmlContent = generateSummaryHTML(data, user)
      break
    case "claims":
      htmlContent = generateClaimsHTML(data, user)
      break
    case "users":
      htmlContent = generateUsersHTML(data, user)
      break
    case "department":
      htmlContent = generateDepartmentHTML(data, user)
      break
    case "audit":
      htmlContent = generateAuditHTML(data, user)
      break
    default:
      htmlContent = `<html><body><h1>Unknown report type</h1></body></html>`
  }

  return htmlContent
}

function generateSummaryPDF(data) {
  const { totalClaims, approvedClaims, rejectedClaims, pendingClaims, totalAmount, approvalRate } = data

  return `
We Care Insurance - Summary Report
Generated: ${new Date().toLocaleString()}

KEY METRICS
===========
Total Claims: ${totalClaims}
Approved Claims: ${approvedClaims}
Rejected Claims: ${rejectedClaims}
Pending Claims: ${pendingClaims}
Total Amount: $${totalAmount.toFixed(2)}
Approval Rate: ${approvalRate.toFixed(2)}%

Report generated by We Care Insurance Management System
  `
}

function generateSummaryHTML(data, user) {
  const { totalClaims, approvedClaims, rejectedClaims, pendingClaims, totalAmount, approvalRate } = data

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Summary Report - ${new Date().toLocaleDateString()}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .metric { background: #f5f5f5; padding: 20px; border-radius: 8px; text-align: center; }
        .metric h3 { margin: 0 0 10px 0; color: #333; }
        .metric p { margin: 0; font-size: 24px; font-weight: bold; color: #007bff; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>We Care Insurance - Summary Report</h1>
        <p>Generated on ${new Date().toLocaleString()} by ${user.name}</p>
      </div>

      <div class="metrics">
        <div class="metric">
          <h3>Total Claims</h3>
          <p>${totalClaims}</p>
        </div>
        <div class="metric">
          <h3>Approved Claims</h3>
          <p>${approvedClaims}</p>
        </div>
        <div class="metric">
          <h3>Rejected Claims</h3>
          <p>${rejectedClaims}</p>
        </div>
        <div class="metric">
          <h3>Pending Claims</h3>
          <p>${pendingClaims}</p>
        </div>
        <div class="metric">
          <h3>Total Amount</h3>
          <p>₱${totalAmount.toFixed(2)}</p>
        </div>
        <div class="metric">
          <h3>Approval Rate</h3>
          <p>${approvalRate.toFixed(1)}%</p>
        </div>
      </div>

      <div class="footer">
        <p>This report was automatically generated from the We Care Insurance Reports & Analytics dashboard.</p>
        <p>Report timestamp: ${new Date().toISOString()}</p>
      </div>
    </body>
    </html>
  `
}

function generateClaimsPDF(data) {
  const { claims, members } = data

  let content = `
We Care Insurance - Claims Report
Generated: ${new Date().toLocaleString()}

CLAIMS SUMMARY
==============
Total Claims: ${claims.length}

CLAIMS DETAILS
==============
`

  claims.forEach((claim) => {
    const member = members.find((m) => m.id === claim.memberId)
    const memberName = member ? member.name : "Unknown"

    content += `
Claim ID: ${claim.id.slice(-8)}
Member: ${memberName}
Type: ${claim.claimType}
Amount: $${claim.amount}
Status: ${claim.status}
Date: ${new Date(claim.createdAt).toLocaleDateString()}
---
`
  })

  content += `
Report generated by We Care Insurance Management System
  `

  return content
}

function generateClaimsHTML(data, user) {
  const { claims, members } = data

  const claimsRows = claims.map((claim) => {
    const member = members.find((m) => m.id === claim.memberId)
    const memberName = member ? member.name : "Unknown"

    return `
      <tr>
        <td>${claim.id.slice(-8)}</td>
        <td>${memberName}</td>
        <td>${claim.claimType}</td>
        <td>₱${parseFloat(claim.amount).toFixed(2)}</td>
        <td>${claim.status}</td>
        <td>${new Date(claim.createdAt).toLocaleDateString()}</td>
      </tr>
    `
  }).join('')

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Claims Report - ${new Date().toLocaleDateString()}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .summary { background: #f5f5f5; padding: 20px; border-radius: 8px; margin-bottom: 30px; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>We Care Insurance - Claims Report</h1>
        <p>Generated on ${new Date().toLocaleString()} by ${user.name}</p>
      </div>

      <div class="summary">
        <h2>Claims Summary</h2>
        <p><strong>Total Claims:</strong> ${claims.length}</p>
      </div>

      <table>
        <thead>
          <tr>
            <th>Claim ID</th>
            <th>Member</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Status</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          ${claimsRows}
        </tbody>
      </table>

      <div class="footer">
        <p>This report was automatically generated from the We Care Insurance Reports & Analytics dashboard.</p>
        <p>Report timestamp: ${new Date().toISOString()}</p>
      </div>
    </body>
    </html>
  `
}

function generateUsersPDF(data) {
  const { users } = data

  let content = `
We Care Insurance - Users Report
Generated: ${new Date().toLocaleString()}

USERS SUMMARY
=============
Total Users: ${users.length}

USERS BY ROLE
=============
`

  const roleCount = {}
  users.forEach((user) => {
    roleCount[user.role] = (roleCount[user.role] || 0) + 1
  })

  Object.entries(roleCount).forEach(([role, count]) => {
    content += `${role}: ${count}\n`
  })

  content += `

USERS DETAILS
=============
`

  users.forEach((user) => {
    content += `
Name: ${user.name}
Email: ${user.email}
Role: ${user.role}
Department: ${user.department}
Status: ${user.status}
---
`
  })

  content += `
Report generated by We Care Insurance Management System
  `

  return content
}

function generateUsersHTML(data, user) {
  const { users } = data

  const roleCount = {}
  users.forEach((u) => {
    roleCount[u.role] = (roleCount[u.role] || 0) + 1
  })

  const roleStats = Object.entries(roleCount).map(([role, count]) => `
    <div style="display: inline-block; margin: 10px; padding: 15px; background: #f0f0f0; border-radius: 8px;">
      <strong>${role}:</strong> ${count}
    </div>
  `).join('')

  const userRows = users.map((u) => `
    <tr>
      <td>${u.name}</td>
      <td>${u.email}</td>
      <td>${u.role}</td>
      <td>${u.department || 'N/A'}</td>
      <td>${u.status}</td>
    </tr>
  `).join('')

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Users Report - ${new Date().toLocaleDateString()}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .summary { background: #f5f5f5; padding: 20px; border-radius: 8px; margin-bottom: 30px; text-align: center; }
        .roles { text-align: center; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>We Care Insurance - Users Report</h1>
        <p>Generated on ${new Date().toLocaleString()} by ${user.name}</p>
      </div>

      <div class="summary">
        <h2>Users Summary</h2>
        <p><strong>Total Users:</strong> ${users.length}</p>
      </div>

      <div class="roles">
        <h3>Users by Role</h3>
        ${roleStats}
      </div>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Department</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${userRows}
        </tbody>
      </table>

      <div class="footer">
        <p>This report was automatically generated from the We Care Insurance Reports & Analytics dashboard.</p>
        <p>Report timestamp: ${new Date().toISOString()}</p>
      </div>
    </body>
    </html>
  `
}

function generateDepartmentPDF(data) {
  const { departments } = data

  let content = `
We Care Insurance - Department Report
Generated: ${new Date().toLocaleString()}

DEPARTMENT SUMMARY
==================
Total Departments: ${departments.length}

DEPARTMENT DETAILS
==================
`

  departments.forEach((dept) => {
    content += `
Department: ${dept.name}
Members: ${dept.memberCount}
Total Claims: ${dept.claimCount}
Total Amount: $${dept.totalAmount.toFixed(2)}
Average Claim: $${dept.averageClaim.toFixed(2)}
---
`
  })

  content += `
Report generated by We Care Insurance Management System
  `

  return content
}

function generateDepartmentHTML(data, user) {
  const { departments } = data

  const departmentRows = departments.map((dept) => `
    <tr>
      <td>${dept.name}</td>
      <td>${dept.memberCount}</td>
      <td>${dept.claimCount}</td>
      <td>₱${dept.totalAmount.toFixed(2)}</td>
      <td>₱${dept.averageClaim.toFixed(2)}</td>
    </tr>
  `).join('')

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Department Report - ${new Date().toLocaleDateString()}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .summary { background: #f5f5f5; padding: 20px; border-radius: 8px; margin-bottom: 30px; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>We Care Insurance - Department Report</h1>
        <p>Generated on ${new Date().toLocaleString()} by ${user.name}</p>
      </div>

      <div class="summary">
        <h2>Department Summary</h2>
        <p><strong>Total Departments:</strong> ${departments.length}</p>
      </div>

      <table>
        <thead>
          <tr>
            <th>Department</th>
            <th>Members</th>
            <th>Total Claims</th>
            <th>Total Amount</th>
            <th>Average Claim</th>
          </tr>
        </thead>
        <tbody>
          ${departmentRows}
        </tbody>
      </table>

      <div class="footer">
        <p>This report was automatically generated from the We Care Insurance Reports & Analytics dashboard.</p>
        <p>Report timestamp: ${new Date().toISOString()}</p>
      </div>
    </body>
    </html>
  `
}

function generateAuditPDF(data) {
  const { logs } = data

  let content = `
We Care Insurance - Audit Report
Generated: ${new Date().toLocaleString()}

AUDIT LOG SUMMARY
=================
Total Entries: ${logs.length}

AUDIT LOG DETAILS
=================
`

  logs.forEach((log) => {
    content += `
Action: ${log.action}
Description: ${log.description}
User ID: ${log.userId}
Timestamp: ${new Date(log.timestamp).toLocaleString()}
---
`
  })

  content += `
Report generated by We Care Insurance Management System
  `

  return content
}

function generateAuditHTML(data, user) {
  const { logs } = data

  const logRows = logs.map((log) => `
    <tr>
      <td>${log.action}</td>
      <td>${log.description}</td>
      <td>${log.userId}</td>
      <td>${new Date(log.timestamp).toLocaleString()}</td>
    </tr>
  `).join('')

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Audit Report - ${new Date().toLocaleDateString()}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .summary { background: #f5f5f5; padding: 20px; border-radius: 8px; margin-bottom: 30px; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>We Care Insurance - Audit Report</h1>
        <p>Generated on ${new Date().toLocaleString()} by ${user.name}</p>
      </div>

      <div class="summary">
        <h2>Audit Log Summary</h2>
        <p><strong>Total Entries:</strong> ${logs.length}</p>
      </div>

      <table>
        <thead>
          <tr>
            <th>Action</th>
            <th>Description</th>
            <th>User ID</th>
            <th>Timestamp</th>
          </tr>
        </thead>
        <tbody>
          ${logRows}
        </tbody>
      </table>

      <div class="footer">
        <p>This report was automatically generated from the We Care Insurance Reports & Analytics dashboard.</p>
        <p>Report timestamp: ${new Date().toISOString()}</p>
      </div>
    </body>
    </html>
  `
}

export function downloadAsText(content, fileName) {
  const element = document.createElement("a")
  element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(content))
  element.setAttribute("download", fileName)
  element.style.display = "none"
  document.body.appendChild(element)
  element.click()
  document.body.removeChild(element)
}

export function downloadAsCSV(data, fileName) {
  let csv = ""

  if (Array.isArray(data) && data.length > 0) {
    const headers = Object.keys(data[0])
    csv = headers.join(",") + "\n"

    data.forEach((row) => {
      const values = headers.map((header) => {
        const value = row[header]
        if (typeof value === "string" && value.includes(",")) {
          return `"${value}"`
        }
        return value
      })
      csv += values.join(",") + "\n"
    })
  }

  const element = document.createElement("a")
  element.setAttribute("href", "data:text/csv;charset=utf-8," + encodeURIComponent(csv))
  element.setAttribute("download", fileName)
  element.style.display = "none"
  document.body.appendChild(element)
  element.click()
  document.body.removeChild(element)
}
